CREATE DATABASE ProjetoDapper
GO

CREATE TABLE PRODUTO
(
	Id INT NOT NULL IDENTITY,
	Description VARCHAR(100) NOT NULL,
	Price DECIMAL(20, 2) NOT NULL,
	CodeBar VARCHAR(100) NOT NULL,
	Stock DECIMAL(20,3) NOT NULL,
	PRIMARY KEY(Id)
);
GO

